package codefolio.client.components.knowledge

import codefolio.client.components.icons.LucideIcons
import japgolly.scalajs.react.*
import japgolly.scalajs.react.vdom.html_<^.*
import org.scalajs.dom

import scala.scalajs.js

/**
 * Wraps the pre-rendered D2 SVG with a fullscreen-zoom modal.
 *
 * The SVG itself is generated by `render.ts` (the D2 WASM engine runs in the markdown pre-pass), arriving in
 * the DOM as raw `<svg>` markup that we don't have a Scala handle on. To preserve the same SVG inside the
 * modal we lift it via `cloneNode(true)` and inject it into a controlled container — same approach as the
 * original Next.js component but driven from the imperative side.
 */
object D2Diagram:

  private val MinZoom = 0.5
  private val MaxZoom = 4.0
  private val Step    = 0.25

  /**
   * `outerHTML` of the source SVG snapshot, captured on mount. We hold this as state (not a DOM ref to the
   * original) so React can render it inside the modal without re-parenting the original element.
   */
  final case class Props(svgHtml: String)

  val Component =
    ScalaFnComponent
      .withHooks[Props]
      .useState(false) // open
      .useState(1.0)   // zoom
      // Body-overflow lock + Escape/+/-/0 keyboard shortcuts while the modal
      // is open. We register the listener imperatively in the dependent
      // effect; the *next* effect run (when `isOpen` toggles back to false)
      // re-enters this block and removes the previous listener via the
      // closure captured in `cleanup`.
      .useRefBy(_ => js.Array[js.Function0[Unit]]())
      // Ref to the wrapper that hosts the cloned SVG inside the modal. Used
      // by the normalization effect below to reach the SVG element.
      .useRefToVdom[dom.html.Div]
      .useEffectWithDepsBy((_, openS, _, _, _) => openS.value) {
        (_, openS, zoomS, cleanupRef, _) => isOpen =>
          // Tear down the prior listener (if any) on every transition.
          val tearDown: Callback = Callback {
            val arr = cleanupRef.value
            for i <- 0 until arr.length do arr(i)()
            cleanupRef.value = js.Array()
          }

          val install: Callback =
            if !isOpen then Callback.empty
            else
              Callback {
                val previousOverflow = dom.document.body.style.overflow
                dom.document.body.style.overflow = "hidden"

                val onKey: js.Function1[dom.KeyboardEvent, Unit] = (e: dom.KeyboardEvent) =>
                  e.key match
                    case "Escape" =>
                      e.preventDefault()
                      openS.setState(false).runNow()
                      zoomS.setState(1.0).runNow()
                    case "+" | "=" =>
                      e.preventDefault()
                      zoomS.modState(z => math.min(MaxZoom, z + Step)).runNow()
                    case "-" =>
                      e.preventDefault()
                      zoomS.modState(z => math.max(MinZoom, z - Step)).runNow()
                    case "0" =>
                      e.preventDefault()
                      zoomS.setState(1.0).runNow()
                    case _ => ()

                dom.document.addEventListener("keydown", onKey)
                cleanupRef.value.push { () =>
                  dom.document.removeEventListener("keydown", onKey)
                  dom.document.body.style.overflow = previousOverflow
                  ()
                }
                ()
              }

          tearDown >> install
      }
      // Normalize the injected SVG once it's in the DOM. Two things are
      // baked-in attributes that CSS can't reach:
      //   1) `preserveAspectRatio` — controls where the diagram sits inside
      //      the SVG box. D2's WASM doesn't always emit `xMidYMid meet`, so
      //      content can end up pinned to a corner of an enlarged box. We
      //      force the centered-letterbox value so the diagram is always
      //      centered inside the white card.
      //   2) `width`/`height` attributes — D2 emits explicit pixel sizes.
      //      Setting `style.width=100%` on the element wins over the attr
      //      AND wins over any class-based attempt (which can lose the
      //      specificity race against the attribute on some setups).
      // We re-run on every open transition because the modal's wrapper
      // unmounts on close; the next open injects a fresh SVG element.
      .useEffectWithDepsBy((_, openS, _, _, _) => openS.value) {
        (_, _, _, _, svgRef) => isOpen =>
          if !isOpen then Callback.empty
          else
            svgRef.foreach { wrapper =>
              val svg = wrapper.querySelector("svg")
              if svg != null then
                svg.setAttribute("preserveAspectRatio", "xMidYMid meet")
                val style = svg.asInstanceOf[js.Dynamic].style
                style.width = "100%"
                style.height = "100%"
                style.display = "block"
            }
      }
      .render { (props, openS, zoomS, _, svgRef) =>
        val close: Callback     = openS.setState(false) >> zoomS.setState(1.0)
        val openModal: Callback = zoomS.setState(1.0) >> openS.setState(true)
        val zoomIn: Callback    = zoomS.modState(z => math.min(MaxZoom, z + Step))
        val zoomOut: Callback   = zoomS.modState(z => math.max(MinZoom, z - Step))
        val zoomReset: Callback = zoomS.setState(1.0)

        <.div(
          // Inline view: the original SVG, with a hover-revealed Zoom button.
          <.div(
            ^.className :=
              "relative group my-6 rounded-lg border border-border bg-card p-4 " +
                "[&_svg]:block [&_svg]:mx-auto [&_svg]:max-w-full [&_svg]:max-h-[420px] " +
                "[&_svg]:h-auto [&_svg]:w-auto",
            <.div(^.dangerouslySetInnerHtml := props.svgHtml),
            <.button(
              ^.tpe := "button",
              ^.onClick --> openModal,
              ^.aria.label := "Open diagram in fullscreen",
              ^.className :=
                "absolute top-2 right-2 inline-flex items-center gap-1 rounded-md bg-background/90 " +
                  "border border-border px-2 py-1 text-xs font-medium text-foreground " +
                  "opacity-0 group-hover:opacity-100 focus-visible:opacity-100 " +
                  "transition-opacity hover:bg-accent",
              LucideIcons.Maximize2(LucideIcons.withClass("h-3.5 w-3.5")),
              "Zoom"
            )
          ),
          // Fullscreen modal.
          if openS.value then
            <.div(
              ^.role       := "dialog",
              ^.aria.modal := true,
              ^.aria.label := "Diagram fullscreen view",
              ^.className  := "fixed inset-0 z-[60] bg-black/80 flex flex-col",
              ^.onClick --> close,
              <.div(
                ^.className := "flex items-center justify-end gap-2 p-3 border-b border-white/10",
                ^.onClick ==> { (e: ReactEvent) => e.stopPropagationCB },
                <.button(
                  ^.tpe := "button",
                  ^.onClick --> zoomOut,
                  ^.aria.label := "Zoom out",
                  ^.className :=
                    "rounded-md bg-background/90 border border-border p-2 hover:bg-accent text-foreground",
                  LucideIcons.ZoomOut(LucideIcons.withClass("h-4 w-4"))
                ),
                <.span(
                  ^.className := "text-xs text-white/80 tabular-nums w-12 text-center",
                  s"${math.round(zoomS.value * 100).toInt}%"
                ),
                <.button(
                  ^.tpe := "button",
                  ^.onClick --> zoomIn,
                  ^.aria.label := "Zoom in",
                  ^.className :=
                    "rounded-md bg-background/90 border border-border p-2 hover:bg-accent text-foreground",
                  LucideIcons.ZoomIn(LucideIcons.withClass("h-4 w-4"))
                ),
                <.button(
                  ^.tpe := "button",
                  ^.onClick --> zoomReset,
                  ^.aria.label := "Reset zoom",
                  ^.className :=
                    "rounded-md bg-background/90 border border-border p-2 hover:bg-accent text-foreground",
                  LucideIcons.RotateCcw(LucideIcons.withClass("h-4 w-4"))
                ),
                <.button(
                  ^.tpe := "button",
                  ^.onClick --> close,
                  ^.aria.label := "Close",
                  ^.className :=
                    "rounded-md bg-background/90 border border-border p-2 hover:bg-accent text-foreground",
                  LucideIcons.X(LucideIcons.withClass("h-4 w-4"))
                )
              ),
              <.div(
                // The scrollable viewport. Uses `flex` (no items-/justify-
                // center) so its lone child gets `margin: auto` for layout.
                // `overflow-auto` here is what provides scrollbars — and
                // because the child is a real layout box (not a transform),
                // both axes scroll naturally when the diagram is zoomed.
                ^.className := "flex-1 overflow-auto flex p-6",
                <.div(
                  ^.onClick ==> { (e: ReactEvent) => e.stopPropagationCB },
                  // Zoom by changing the card's actual dimensions, NOT via
                  // `transform: scale`. Transform doesn't grow the layout
                  // box, so the browser's scroll machinery has nothing to
                  // scroll into; resizing the box gives true overflow that
                  // overflow-auto can latch onto.
                  ^.style := js.Dynamic
                    .literal(
                      width = s"${85.0 * zoomS.value}vw",
                      height = s"${78.0 * zoomS.value}vh"
                    )
                    .asInstanceOf[js.Object],
                  // `m-auto` on a flex item is the classic trick that both
                  // (a) centers when there's free space, and (b) preserves
                  // SYMMETRIC overflow when there isn't — which is what
                  // makes scroll-left work past 100% zoom. `justify-center`
                  // on the parent does NOT do that; it clips the start
                  // side. `shrink-0` keeps the card at its declared size
                  // even when narrower than the parent.
                  ^.className :=
                    "m-auto shrink-0 bg-white rounded-lg p-6 " +
                      "transition-[width,height] duration-150 ease-out",
                  <.div.withRef(svgRef)(
                    // The SVG itself is sized + aspect-ratio'd by the
                    // post-mount normalization effect (see above) — that
                    // way we don't have to fight class-vs-attribute
                    // specificity, and we can override `preserveAspectRatio`
                    // which is reachable only as an attribute.
                    ^.className               := "w-full h-full",
                    ^.dangerouslySetInnerHtml := props.svgHtml
                  )
                )
              )
            )
          else EmptyVdom
        )
      }
