package codefolio.client.components.cortex

import codefolio.client.components.icons.LucideIcons
import japgolly.scalajs.react.*
import japgolly.scalajs.react.vdom.html_<^.*
import org.scalajs.dom

import scala.scalajs.js

/**
 * Wraps the pre-rendered D2 SVG with a fullscreen-zoom modal.
 *
 * The SVG itself is generated by `render.ts` (the D2 WASM engine runs in the markdown pre-pass), arriving in
 * the DOM as raw `<svg>` markup that we don't have a Scala handle on. To preserve the same SVG inside the
 * modal we lift it via `cloneNode(true)` and inject it into a controlled container — same approach as the
 * original Next.js component but driven from the imperative side.
 */
object D2Diagram:

  private val MinZoom = 0.5
  private val MaxZoom = 4.0
  private val Step    = 0.25

  /**
   * `outerHTML` of the source SVG snapshot, captured on mount. We hold this as state (not a DOM ref to the
   * original) so React can render it inside the modal without re-parenting the original element.
   */
  final case class Props(svgHtml: String)

  val Component =
    ScalaFnComponent
      .withHooks[Props]
      .useState(false)
      .useState(1.0)
      .useRefBy(_ => js.Array[js.Function0[Unit]]())
      .useEffectWithDepsBy((_, openS, _, _) => openS.value) {
        (_, openS, zoomS, cleanupRef) => isOpen =>
          val tearDown: Callback = Callback {
            val arr = cleanupRef.value
            for i <- 0 until arr.length do arr(i)()
            cleanupRef.value = js.Array()
          }

          val install: Callback =
            if !isOpen then Callback.empty
            else
              Callback {
                val previousOverflow = dom.document.body.style.overflow
                dom.document.body.style.overflow = "hidden"

                val onKey: js.Function1[dom.KeyboardEvent, Unit] = (e: dom.KeyboardEvent) =>
                  e.key match
                    case "Escape" =>
                      e.preventDefault()
                      openS.setState(false).runNow()
                      zoomS.setState(1.0).runNow()
                    case "+" | "=" =>
                      e.preventDefault()
                      zoomS.modState(z => math.min(MaxZoom, z + Step)).runNow()
                    case "-" =>
                      e.preventDefault()
                      zoomS.modState(z => math.max(MinZoom, z - Step)).runNow()
                    case "0" =>
                      e.preventDefault()
                      zoomS.setState(1.0).runNow()
                    case _ => ()

                dom.document.addEventListener("keydown", onKey)
                cleanupRef.value.push { () =>
                  dom.document.removeEventListener("keydown", onKey)
                  dom.document.body.style.overflow = previousOverflow
                  ()
                }
                ()
              }

          tearDown >> install
      }
      .render { (props, openS, zoomS, _) =>
        val close: Callback     = openS.setState(false) >> zoomS.setState(1.0)
        val openModal: Callback = zoomS.setState(1.0) >> openS.setState(true)
        val zoomIn: Callback    = zoomS.modState(z => math.min(MaxZoom, z + Step))
        val zoomOut: Callback   = zoomS.modState(z => math.max(MinZoom, z - Step))
        val zoomReset: Callback = zoomS.setState(1.0)

        <.div(
          <.div(
            ^.className := "diagram group not-prose",
            <.div(^.dangerouslySetInnerHtml := props.svgHtml),
            <.button(
              ^.tpe := "button",
              ^.onClick --> openModal,
              ^.aria.label := "Open diagram in fullscreen",
              ^.className  := "diagram__zoom-button",
              LucideIcons.Maximize2(LucideIcons.withClass("diagram__zoom-icon")),
              "Zoom"
            )
          ),
          if openS.value then
            <.div(
              ^.role       := "dialog",
              ^.aria.modal := true,
              ^.aria.label := "Diagram fullscreen view",
              ^.className  := "diagram-modal not-prose",
              ^.onClick --> close,
              <.div(
                ^.className := "diagram-modal__toolbar",
                ^.onClick ==> { (e: ReactEvent) => e.stopPropagationCB },
                <.button(
                  ^.tpe := "button",
                  ^.onClick --> zoomOut,
                  ^.aria.label := "Zoom out",
                  ^.className  := "diagram-modal__button",
                  LucideIcons.ZoomOut(LucideIcons.withClass("diagram-modal__button-icon"))
                ),
                <.span(
                  ^.className := "diagram-modal__zoom-readout",
                  s"${math.round(zoomS.value * 100).toInt}%"
                ),
                <.button(
                  ^.tpe := "button",
                  ^.onClick --> zoomIn,
                  ^.aria.label := "Zoom in",
                  ^.className  := "diagram-modal__button",
                  LucideIcons.ZoomIn(LucideIcons.withClass("diagram-modal__button-icon"))
                ),
                <.button(
                  ^.tpe := "button",
                  ^.onClick --> zoomReset,
                  ^.aria.label := "Reset zoom",
                  ^.className  := "diagram-modal__button",
                  LucideIcons.RotateCcw(LucideIcons.withClass("diagram-modal__button-icon"))
                ),
                <.button(
                  ^.tpe := "button",
                  ^.onClick --> close,
                  ^.aria.label := "Close",
                  ^.className  := "diagram-modal__button",
                  LucideIcons.X(LucideIcons.withClass("diagram-modal__button-icon"))
                )
              ),
              <.div(
                ^.className := "diagram-modal__viewport",
                <.div(
                  ^.onClick ==> { (e: ReactEvent) => e.stopPropagationCB },
                  ^.style := js.Dynamic
                    .literal(
                      width = s"${85.0 * zoomS.value}vw",
                      height = s"${78.0 * zoomS.value}vh"
                    )
                    .asInstanceOf[js.Object],
                  ^.className := "diagram-modal__card",
                  <.div(
                    ^.className               := "diagram-modal__svg not-prose",
                    ^.dangerouslySetInnerHtml := props.svgHtml
                  )
                )
              )
            )
          else EmptyVdom
        )
      }
